export default {
  login: "abdelnaby1",
  id: 44681514,
  node_id: "MDQ6VXNlcjQ0NjgxNTE0",
  avatar_url: "https://avatars.githubusercontent.com/u/44681514?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/abdelnaby1",
  html_url: "https://github.com/abdelnaby1",
  followers_url: "https://api.github.com/users/abdelnaby1/followers",
  following_url:
    "https://api.github.com/users/abdelnaby1/following{/other_user}",
  gists_url: "https://api.github.com/users/abdelnaby1/gists{/gist_id}",
  starred_url: "https://api.github.com/users/abdelnaby1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/abdelnaby1/subscriptions",
  organizations_url: "https://api.github.com/users/abdelnaby1/orgs",
  repos_url: "https://api.github.com/users/abdelnaby1/repos",
  events_url: "https://api.github.com/users/abdelnaby1/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/abdelnaby1/received_events",
  type: "User",
  site_admin: false,
  name: "Ahmed Abdelnaby",
  company: null,
  blog: "",
  location: "Egypt, Cairo",
  email: null,
  hireable: null,
  bio: "i'm interested in software engineering",
  twitter_username: null,
  public_repos: 23,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-11-01T18:42:30Z",
  updated_at: "2022-03-31T21:33:08Z",
};
